### ISSUE TITLE
Unable to assign imported data to "Spectra" variable

### ISSUE THREAD

**Issue by tanlingqiao** [csmsoftware/IMPaCTS#1]
Hi, good day!
I have cloned IMPaCTS directory on GitHub to my local desktop, and tried to run the matlab codes, but I faced a problem when I want to assign the imported data to “spectra” variable. By referring to the screenshot as attached, “oneDWS” is empty map container, so when I tried to assign the imported data by using this command “spectra = imported.oneDWS('Serum')”, the command does not work. Could you help us to check on this?
![screenshot from matlab](https://user-images.githubusercontent.com/32443329/31061402-967c6698-a753-11e7-9b9b-eb009d1ec8f6.png)

**Comment by gordondavies** [comment]
Hi!

It looks like the import failed at some point - as the 'imported.import_failed' map container has 3 entries in it.

The import errors are broken into pulse programs - so to see the oneDWS import errors, inspect the following variable:
`imported.import_errors('noesygppr1d')`
This will show the error stacks for the import, and should guide to where the problem lies.

Import errors are often caused by a mismatch between the entries in the import Excel files and what is found in the Bruker folders.

More info on this can be found here:
https://csmsoftware.github.io/docs/impacts/import-raw-bruker.html#output

Regards,

Gordon

**Comment by tanlingqiao** [comment]
Hi Gordon,

Thanks for your prompt reply. I have checked the import_error by using command that you mentioned "imported.import_errors('noesygppr1d')", and I still can't fix the errors, can you help? Screenshot of the error is as below:

![screenshot from 2017-10-04 10-47-06](https://user-images.githubusercontent.com/32443329/31158142-3ecb65ca-a8f2-11e7-840b-b2bfa813bbbb.png)

**Comment by gordondavies** [comment]
Hi Tanling,

Can you post the contents of the stack variable? One will do. This will
hopefully identify which variable is being incorrectly passed as a 'char'.

Regards,

Gordon

**Comment by tanlingqiao** [comment]
Hi Gordon,

I have already figured out the error, and the problem was fixed. 
many thanks for your advises and helps! :)
